name: Build EXE

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycomm3 pyinstaller

      - name: Build exe
        run: |
          pyinstaller --noconsole --onefile --icon CA.ico --add-data "CA.png;." seq_tester.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sequence-Transfer-Tool
          path: dist\seq_tester.exe
